MeetingSignIn/Models/Meeting.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Runtime.Remoting.Contexts;
using System.Web;

namespace MeetingSignIn.Models
{
    public class Meeting
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public String Theme { get; set; }
        public String Owner { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public List<Member> Members { get; set; }
        private int _signinCount = 0;
        public bool Completed { get; set; }
        public string Newest { get; set; }

        [MethodImpl(MethodImplOptions.Synchronized)]
        public bool Signin(string alias)
        {
            var member = Members.Find(m => m.Alias.Equals(alias) && !m.Signed);
            if (member == null)
            {
                return false;
            }
            member.Signed = true;
            Newest = alias;
            _signinCount++;
            if (_signinCount == Members.Count)
            {
                Completed = true;
            }
            return true;
        }
    }
}

MeetingSignIn/Controllers/MeetingsController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using MeetingSignIn.Models;

namespace MeetingSignIn.Controllers
{
    public class MeetingsController : Controller
    {
        private static readonly object Indexlock = new object();
        private static readonly object MeetingLock = new object();
        private readonly List<Meeting> activeMeetings = Cache.ActiveMeetings;
        private readonly MeetingContext db = new MeetingContext();
        private readonly Dictionary<string, List<Meeting>> index = Cache.Index;
        private readonly List<Meeting> tempMeetings = Cache.TempMeetings;

        public ActionResult Signin(string alias)
        {
            if (!ModelState.IsValid || alias == null)
            {
                return ErrorResult(1, ModelState.ToString());
            }

            lock (Indexlock)
            {
                if (index.ContainsKey(alias) && index[alias].Count > 0)
                {
                    return JsonResult(
                        new
                        {
                            result = new { status = 0, message = "meetings can be signed in" },
                            meetings = index[alias]
                        });
                }
            }
            return ErrorResult(4, "No meeting found with alias " + alias);
        }

        public ActionResult SigninMeeting(string alias, int meetingId)
        {
            if (!ModelState.IsValid || alias == null)
            {
                return ErrorResult(1, ModelState.ToString());
            }
            var meeting = activeMeetings.Find(m => m.Id == meetingId);
            if (meeting == null)
            {
                return ErrorResult(5, "No active meeting found with meeting id " + meetingId);
            }
            if (meeting.Signin(alias))
            {
                RemoveIndex(alias, meeting);
            }
            if (meeting.Completed)
            {
                lock (MeetingLock)
                {
                    activeMeetings.Remove(meeting);
                }
            }
            return JsonResult(
                new
                {
                    result = new { status = 0, message = "sign in a meeting successful. meeting theme is" + meeting.Theme },
                    meeting = meeting
                });
        }

        public async Task<ActionResult> Start(string alias)
        {
            if (!ModelState.IsValid || alias == null)
            {
                return ErrorResult(1, ModelState.ToString());
            }
            var meetings = await GetMeetingsFromSharePoint(alias);
            meetings = meetings.FindAll(m => !activeMeetings.Exists(am => am.Id == m.Id));
            if (meetings.Count == 0)
            {
                return ErrorResult(2, "No nonactive meeting found with alias" + alias);
            }
            lock (MeetingLock)
            {
                tempMeetings.AddRange(meetings.FindAll(m => !tempMeetings.Exists(tm => tm.Id == m.Id)));
            }
            return JsonResult(
                new
                {
                    result = new { status = 0, message = "meetings can be started" },
                    meetings = meetings
                });

        }

        public ActionResult StartMeeting(string alias, int meetingId)
        {
            if (!ModelState.IsValid || alias == null)
            {
                return ErrorResult(1, ModelState.ToString());
            }
            var meeting = tempMeetings.Find(m => m.Id == meetingId);
            if (meeting == null)
            {
                return ErrorResult(3, "No meeting found with meeting id" + meetingId);
            }
            lock (MeetingLock)
            {
                tempMeetings.Remove(meeting);
                activeMeetings.Add(meeting);
                meeting.Newest = alias;
            }
            AddIndex(meeting);
            return JsonResult(
                new
                {
                    result = new { status = 0, message = "start a meeting successful. meeting theme is" + meeting.Theme },
                    meeting = meeting
                });
        }

        public ActionResult ShowMeeting(string alias)
        {
            if (!ModelState.IsValid || alias == null)
            {
                return Content("invalid parameter");
            }
            var meeting = activeMeetings.Find(m => m.Owner.Equals(alias));
            if (meeting == null)
            {
                return HttpNotFound();
            }
            var persons = meeting.Members.Where(m => m.Signed).Select(
                m => m.Alias).ToList() ?? new List<string>();
            persons.Add(alias);
            var newest = db.Persons.Find(meeting.Newest);
            var owner = db.Persons.Find(meeting.Owner);
            ViewData["alias"] = alias;
            ViewData["persons"] = persons;
            ViewData["newest"] = newest;
            ViewData["owner"] = owner;
            return View();
            //    JsonResult(new
            //{
            //    persons = persons.ToList(),
            //    newest = newest,
            //    owner = owner
            //});
        }

        public ActionResult Login()
        {
            return this.View();
        }

        [NonAction]
        private void AddIndex(Meeting meeting)
        {
            Task.Run(
                () =>
                    {
                        lock (Indexlock)
                        {
                            meeting.Members.ForEach(
                                m =>
                                    {
                                        if (index.ContainsKey(m.Alias))
                                        {
                                            index[m.Alias].Add(meeting);
                                        }
                                        else
                                        {
                                            index[m.Alias] = new List<Meeting> { meeting };
                                        }
                                    });
                        }
                    });
        }

        [NonAction]
        private async Task<List<Meeting>> GetMeetingsFromSharePoint(string alias)
        {
            return await db.Meetings.Include(m => m.Members).Where(m => m.Owner.Equals(alias)).ToListAsync();
        }

        [NonAction]
        private void RemoveIndex(string alias, Meeting meeting)
        {
            lock (Indexlock)
            {
                var value = index[alias];
                if (value != null)
                    value.Remove(meeting);
            }
        }
        [NonAction]
        private JsonResult ErrorResult(int status, string str)
        {
            return JsonResult(
                new
                {
                    result = new { status = status, message = str }
                });
        }
        [NonAction]
        private JsonResult JsonResult(object data)
        {
            return Json(data, "application/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }
    }
}

MeetingSignIn/Views/Meetings/Create.cshtml
@model MeetingSignIn.Models.Meeting

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Meeting</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Theme, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Theme, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Theme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Owner, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Owner, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Owner, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Completed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Completed)
                    @Html.ValidationMessageFor(model => model.Completed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MeetingSignIn/Views/Meetings/Delete.cshtml
@model MeetingSignIn.Models.Meeting

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Meeting</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Theme)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Theme)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Owner)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Owner)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Completed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Completed)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MeetingSignIn/Views/Meetings/Details.cshtml
@model MeetingSignIn.Models.Meeting

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Meeting</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Theme)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Theme)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Owner)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Owner)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Completed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Completed)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MeetingSignIn/Views/Meetings/Edit.cshtml
@model MeetingSignIn.Models.Meeting

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Meeting</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Theme, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Theme, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Theme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Owner, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Owner, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Owner, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Completed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Completed)
                    @Html.ValidationMessageFor(model => model.Completed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MeetingSignIn/Views/Meetings/Login.cshtml
<h2>Login</h2>
<br />
<br />

    @using (Html.BeginForm("ShowMeeting", "Meetings")) {
    <div>
        Enter your name: @Html.TextBox("alias")
    </div>
        
    <div>
        <input type="submit" value="Submit" />
    </div>
     }

MeetingSignIn/Views/Meetings/ShowMeeting.cshtml
@model IEnumerable<MeetingSignIn.Models.Person>
@{
    ViewBag.Title = "ShowMeeting";
}
@using MeetingSignIn.Models;
<!DOCTYPE html>
<html>
<head>
    <link href="~/Content/bootstrap.min.css" type="text/css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js" type="text/javascript"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>

    <h2>Meeting Introduction</h2>
    <h2 id="test">@Html.Encode(ViewData["alias"]) </h2>
    <table>
        <tr>
            <td>
                <h3 style="text-align:center">Member Name</h3>
                <div style="text-align:center;width:300px;height:auto">

                    @foreach (var item in ViewData["persons"] as List<string>)
                    {
                        <p>@item</p>
                    }
                </div>
            </td>
            <td style="width:500px;text-align:center">
                <div id="myCarousel" class="carousel slide">
                    <div class="carousel-inner">
                        @foreach (var item in ViewData["newest"] as List<Person>)
                        {
                            <div class="item">
                                <h3>Person information</h3>
                                <div>
                                    <div style="float:left;width:49%;text-align:right">
                                        <img src=@((ViewData["newest"] as Person).Photo) width="120" height="180" alt="照片" />
                                        @*<img src="~/Content/c8ea15ce36d3d5394b6361c33887e950352ab050.jpg" width="80" height="120" alt="照片" />*@
                                    </div>
                                    <div style="float:right;width:49%;text-align:left">
                                        <h4 style="width:400px"><strong>AliasName:</strong></h4>
                                        <p style="width:400px">@item.Alias</p>
                                        <h4 style="width:400px"><strong>department:</strong></h4>
                                        <p style="width:400px">@item.DepartMent</p>
                                    </div>
                                </div>
                                <div style="float:right">
                                    <h4 style="text-align:left;width:400px;"><strong>Information:</strong></h4>
                                    <p style="word-wrap: break-word; word-break: break-all;width:300px;text-align:left">@item.Infomation</p>
                                </div>
                            </div>
                        }


                    </div>
                    <a class="carousel-control left" href="#myCarousel"
                       data-slide="prev">&lsaquo;</a>
                    <a class="carousel-control right" href="#myCarousel"
                       data-slide="next">&rsaquo;</a>
                </div>
            </td>
        </tr>
    </table>

    <script>

        $().ready(function () {

            $($($(".carousel-inner").children()).get(0)).addClass("active");
            setInterval(function () { $.post("ShowMeeting", { alias: $('#test').text() }, function (data) { }) }, 3000);
        })
    </script>
</body>
</html>